#!/usr/bin/env python3
"""Embed broker/sprig-broker into sprig.el as `sprig--broker-source-text'.

The broker is shipped to hosts over SSH, but package managers such as straight
ship only .el files, so a broker/ dir beside the loaded library is not there to
read.  sprig.el therefore carries the script's bytes in a defconst, regenerated
by this script whenever the broker changes.  A test guards that the two match.

Run from anywhere:  python3 broker/embed.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BROKER = os.path.join(HERE, "sprig-broker")
SPRIG = os.path.join(HERE, os.pardir, "sprig.el")
BEGIN = ";;;; broker-source-begin (generated by broker/embed.py; do not edit by hand)"
END = ";;;; broker-source-end"


def elisp_string(text):
    # Only backslash and double-quote need escaping in an Elisp string literal;
    # newlines stay literal so the diff is legible.
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    with open(BROKER, "r", encoding="utf-8") as f:
        source = f.read()
    block = (
        BEGIN + "\n"
        "(defconst sprig--broker-source-text\n"
        + elisp_string(source) + "\n"
        '  "Embedded copy of broker/sprig-broker, shipped to a host on first use.\n'
        "Generated by broker/embed.py; the test\n"
        "`sprig-test-broker-source-matches-file' guards that it matches the\n"
        'script.  Regenerate with broker/embed.py after editing the broker.")\n'
        + END
    )
    with open(SPRIG, "r", encoding="utf-8") as f:
        sprig = f.read()
    i = sprig.index(BEGIN)
    j = sprig.index(END) + len(END)
    sprig = sprig[:i] + block + sprig[j:]
    with open(SPRIG, "w", encoding="utf-8") as f:
        f.write(sprig)
    print(f"embedded {len(source)} bytes into sprig.el")


if __name__ == "__main__":
    main()
